labels: ["bug"]
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        
        Report a bug or unexpected behavior in Indexa.
        
        **For security vulnerabilities:** Email security@indexa.site instead
        
        **Before submitting:**
        - Check the [Troubleshooting guide](https://github.com/Team-Indexa/indexa/blob/main/Docs/faq.md#troubleshooting)
        - Search existing bug reports

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "Clear and concise description of what went wrong"
      placeholder: "When I search for 'X', I expected 'Y' but got 'Z'"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "How can we reproduce this bug?"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Search for '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
      placeholder: "I expected the search to return..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Instead, I saw..."
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: "Browser"
      description: "Which browser are you using?"
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Brave
        - Opera
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: "Browser Version"
      description: "What version of the browser?"
      placeholder: "e.g., 120.0.6099.109"
    validations:
      required: false

  - type: dropdown
    id: device
    attributes:
      label: "Device Type"
      description: "What device are you using?"
      options:
        - Desktop - Windows
        - Desktop - macOS
        - Desktop - Linux
        - Mobile - iOS
        - Mobile - Android
        - Tablet
        - Other
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: "Frequency"
      description: "How often does this happen?"
      options:
        - Always - 100%
        - Often - 75%
        - Sometimes - 50%
        - Rarely - 25%
        - Once - Can't reproduce
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots/Videos"
      description: "If applicable, add screenshots or screen recordings"
      placeholder: "Drag and drop images here..."
    validations:
      required: false

  - type: textarea
    id: console
    attributes:
      label: "Console Errors"
      description: "Any errors in browser console? (F12 → Console tab)"
      placeholder: "Paste console errors here..."
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Pre-submission Checklist"
      description: "Please confirm:"
      options:
        - label: "I've searched for similar bug reports"
          required: true
        - label: "I've provided clear steps to reproduce"
          required: true
        - label: "This is not a security vulnerability (use security@indexa.site for those)"
          required: true
