labels: ["question"]
title: "[Q&A] "
body:
  - type: markdown
    attributes:
      value: |
        ## Question & Answer
        
        Ask questions about using Indexa, search features, or general functionality.
        
        **Before posting:**
        - Check the [FAQ](https://github.com/Team-Indexa/indexa/blob/main/Docs/faq.md)
        - Search existing discussions
        - Review the [Documentation](https://github.com/Team-Indexa/indexa/blob/main/README.md)

  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      description: "What would you like to know?"
      placeholder: "I'd like to understand how..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Provide any relevant context, what you've tried, or where you looked"
      placeholder: "I checked the FAQ but didn't find..."
    validations:
      required: false

  - type: dropdown
    id: topic
    attributes:
      label: "Topic"
      description: "What is this question about?"
      options:
        - Search functionality
        - Dufus AI
        - Privacy & Security
        - Account & OwlGuard
        - Shopping Search
        - Image Search
        - API & Developers
        - Self-hosting
        - Performance
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "Pre-submission Checklist"
      description: "Please confirm you've done the following:"
      options:
        - label: "I've searched for similar questions"
          required: true
        - label: "I've checked the FAQ"
          required: true
        - label: "I've reviewed the documentation"
          required: true
